### ISSUE TITLE
[1.1.1] ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by moseb** [realpython/django-slow-tests#30]
We started getting these errors recently:
```
FAILED (errors=1)
Traceback (most recent call last):
  File "/usr/src/app/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/test.py", line 23, in run_from_argv
    super().run_from_argv(argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/test.py", line 53, in handle
    failures = test_runner.run_tests(test_labels)
  File "/usr/local/lib/python3.7/site-packages/moto/core/models.py", line 80, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/moto/core/models.py", line 80, in wrapper
    result = func(*args, **kwargs)
  File "/usr/src/app/moberries/utils/test_clients.py", line 32, in run_tests
    return super().run_tests(test_labels, extra_tests, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/test/runner.py", line 646, in run_tests
    return self.suite_result(suite, result)
  File "/usr/local/lib/python3.7/site-packages/django_slowtests/testrunner.py", line 239, in suite_result
    timings = self.get_timings()
  File "/usr/local/lib/python3.7/site-packages/django_slowtests/testrunner.py", line 214, in get_timings
    name, duration = line.strip('\n').split(',')
ValueError: too many values to unpack (expected 2)
```
Could be related to #20 — we have Django 2.2.6.

**Comment by moseb** [comment]
Any thoughts?

**Comment by moseb** [comment]
Turns out that a local file from previous runs was causing the problem: Deleting that file fixed the issue. I'll close the ticket; please feel free to re-open as needed.
